package com.github.mperry

import fj.F1Functions
import fj.F2Functions
import fj.data.Stream
import fj.data.Stream.cons

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
 * starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms
 */
class Problem2 {

    fun fibs(a: Int, b: Int): Stream<Int> = Stream.cons(a, { fibs(b, a + b)})

}